apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mail-core.fullname" . }}-postfix
  labels:
    {{- include "mail-core.labels" . | nindent 4 }}
    component: postfix
spec:
  replicas: {{ .Values.postfix.replicaCount }}
  selector:
    matchLabels:
      {{- include "mail-core.selectorLabels" . | nindent 6 }}
      component: postfix
  template:
    metadata:
      labels:
        {{- include "mail-core.selectorLabels" . | nindent 8 }}
        component: postfix
    spec:
      containers:
      - name: postfix
        image: "{{ .Values.postfix.image.repository }}:{{ .Values.postfix.image.tag }}"
        imagePullPolicy: {{ .Values.postfix.image.pullPolicy }}
        ports:
        - name: smtp
          containerPort: 25
          protocol: TCP
        - name: submission
          containerPort: 587
          protocol: TCP
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.postgresql.host | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.database | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.username | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mail-core.fullname" . }}-postgresql
              key: password
        volumeMounts:
        - name: postfix-config
          mountPath: /etc/postfix/main.cf
          subPath: main.cf
        - name: mail-spool
          mountPath: /var/spool/postfix
        livenessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.postfix.resources | nindent 10 }}
      volumes:
      - name: postfix-config
        configMap:
          name: {{ include "mail-core.fullname" . }}-postfix-config
      - name: mail-spool
        persistentVolumeClaim:
          claimName: {{ include "mail-core.fullname" . }}-mail-spool
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mail-core.fullname" . }}-postfix
  labels:
    {{- include "mail-core.labels" . | nindent 4 }}
    component: postfix
spec:
  type: {{ .Values.postfix.service.type }}
  ports:
  - port: 25
    targetPort: smtp
    protocol: TCP
    name: smtp
  - port: 587
    targetPort: submission
    protocol: TCP
    name: submission
  selector:
    {{- include "mail-core.selectorLabels" . | nindent 4 }}
    component: postfix
